---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: {{ .Values.driver.name }}
  labels:
    {{- include "blob.labels" . | nindent 4 }}
spec:
  attachRequired: false
  podInfoOnMount: true
  fsGroupPolicy: {{ .Values.feature.fsGroupPolicy }}
  volumeLifecycleModes:
    - Persistent
    - Ephemeral
  tokenRequests:
    - audience: api://AzureADTokenExchange
