---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-blob-node
  namespace: kube-system
spec:
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      app: csi-blob-node
  template:
    metadata:
      labels:
        app: csi-blob-node
    spec:
      hostNetwork: true
      hostPID: true
      dnsPolicy: Default
      serviceAccountName: csi-blob-node-sa
      nodeSelector:
        kubernetes.io/os: linux
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: NotIn
                    values:
                      - virtual-kubelet
      priorityClassName: system-node-critical
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      tolerations:
        - operator: "Exists"
      initContainers:
        - name: install-blobfuse-proxy
          image: mcr.microsoft.com/oss/kubernetes-csi/blob-csi:v1.25.6
          imagePullPolicy: IfNotPresent
          command:
            - "/blobfuse-proxy/init.sh"
          securityContext:
            privileged: true
            capabilities:
              drop:
                - ALL
          env:
            - name: DEBIAN_FRONTEND
              value: "noninteractive"
            - name: INSTALL_BLOBFUSE_PROXY
              value: "true"
            - name: INSTALL_BLOBFUSE
              value: "false"
            - name: BLOBFUSE_VERSION
              value: "1.4.5"
            - name: INSTALL_BLOBFUSE2
              value: "true"
            - name: BLOBFUSE2_VERSION
              value: "2.4.1"
            - name: SET_MAX_OPEN_FILE_NUM
              value: "true"
            - name: MAX_FILE_NUM
              value: "9000000"
            - name: DISABLE_UPDATEDB
              value: "true"
          volumeMounts:
            - name: host-usr
              mountPath: /host/usr
            - name: host-usr-local
              mountPath: /host/usr/local
            - name: host-etc
              mountPath: /host/etc
      containers:
        - name: liveness-probe
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
          image: mcr.microsoft.com/oss/kubernetes-csi/livenessprobe:v2.15.0
          args:
            - --csi-address=/csi/csi.sock
            - --probe-timeout=10s
            - --http-endpoint=localhost:29633
            - --v=2
          resources:
            limits:
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 20Mi
          securityContext:
            capabilities:
              drop:
                - ALL
        - name: node-driver-registrar
          image: mcr.microsoft.com/oss/kubernetes-csi/csi-node-driver-registrar:v2.13.0
          args:
            - --csi-address=$(ADDRESS)
            - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
            - --v=2
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: /var/lib/kubelet/plugins/blob.csi.azure.com/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
          resources:
            limits:
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 20Mi
          securityContext:
            capabilities:
              drop:
                - ALL
        - name: blob
          image: mcr.microsoft.com/oss/kubernetes-csi/blob-csi:v1.25.6
          imagePullPolicy: IfNotPresent
          args:
            - "--v=5"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--enable-blobfuse-proxy=true"
            - "--blobfuse-proxy-endpoint=$(BLOBFUSE_PROXY_ENDPOINT)"
            - "--nodeid=$(KUBE_NODE_NAME)"
            - "--user-agent-suffix=OSS-kubectl"
            - "--metrics-address=0.0.0.0:29635"
            - "--enable-aznfs-mount=true"
          ports:
            - containerPort: 29635
              name: metrics
              protocol: TCP
          livenessProbe:
            failureThreshold: 5
            httpGet:
              host: localhost
              path: /healthz
              port: 29633
            initialDelaySeconds: 30
            timeoutSeconds: 30
            periodSeconds: 30
          env:
            - name: AZURE_CREDENTIAL_FILE
              valueFrom:
                configMapKeyRef:
                  name: azure-cred-file
                  key: path
                  optional: true
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: BLOBFUSE_PROXY_ENDPOINT
              value: unix:///csi/blobfuse-proxy.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          securityContext:
            privileged: true
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
            - mountPath: /var/lib/kubelet/
              mountPropagation: Bidirectional
              name: mountpoint-dir
            - mountPath: /etc/kubernetes/
              name: azure-cred
            - mountPath: /mnt
              name: blob-cache
            - mountPath: /opt/microsoft/aznfs/data
              name: aznfs-data
            - mountPath: /lib/modules
              name: lib-modules
              readOnly: true
          resources:
            limits:
              memory: 2100Mi
            requests:
              cpu: 10m
              memory: 20Mi
        - name: aznfswatchdog
          image: mcr.microsoft.com/oss/kubernetes-csi/blob-csi:v1.25.6
          command:
            - "aznfswatchdog"
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
            capabilities:
              drop:
                - ALL
          resources:
            limits:
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 20Mi
          volumeMounts:
            - mountPath: /opt/microsoft/aznfs/data
              name: aznfs-data
            - mountPath: /var/lib/kubelet/
              mountPropagation: Bidirectional
              name: mountpoint-dir
      volumes:
        - name: host-usr
          hostPath:
            path: /usr
        - name: host-usr-local
          hostPath:
            path: /usr/local
        - name: host-etc
          hostPath:
            path: /etc
        - hostPath:
            path: /var/lib/kubelet/plugins/blob.csi.azure.com
            type: DirectoryOrCreate
          name: socket-dir
        - hostPath:
            path: /var/lib/kubelet/
            type: DirectoryOrCreate
          name: mountpoint-dir
        - hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: DirectoryOrCreate
          name: registration-dir
        - hostPath:
            path: /etc/kubernetes/
            type: DirectoryOrCreate
          name: azure-cred
        - hostPath:
            path: /mnt
            type: DirectoryOrCreate
          name: blob-cache
        - hostPath:
            path: /opt/microsoft/aznfs/data
            type: DirectoryOrCreate
          name: aznfs-data
        - name: lib-modules
          hostPath:
            path: /lib/modules
            type: DirectoryOrCreate
---
