allow-other: true

logging:
  type: base
  level: log_debug

components:
  - libfuse
  - file_cache
  - attr_cache
  - azstorage

libfuse:
  attribute-expiration-sec: 120
  entry-expiration-sec: 120
  negative-entry-expiration-sec: 240

file_cache:
  timeout-sec: 120
  max-size-mb: 4096

attr_cache:
  timeout-sec: 7200
