---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: blob.csi.azure.com
spec:
  attachRequired: false
  podInfoOnMount: true
  fsGroupPolicy: ReadWriteOnceWithFSType
  volumeLifecycleModes:
    - Persistent
    - Ephemeral
  requiresRepublish: true
  tokenRequests:
    - audience: api://AzureADTokenExchange
      expirationSeconds: 3600
