syntax = "proto3";

option go_package = ".;pb";

message MountAzureBlobRequest {
	string mountArgs = 1;
	repeated string authEnv = 2;
	string protocol = 3;
}

message MountAzureBlobResponse {
	string output = 1;
}

message BlobfuseCapabilitiesRequest {
	string protocol = 1;
}

message BlobfuseCapabilitiesResponse {
	bool distributedCacheSupported = 1;
}

service MountService {
	rpc MountAzureBlob(MountAzureBlobRequest) returns (MountAzureBlobResponse) {};
	rpc GetBlobfuseCapabilities(BlobfuseCapabilitiesRequest) returns (BlobfuseCapabilitiesResponse) {};
}
