{{- if .Values.node.enableBlobfuseProxy -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: csi-blobfuse-proxy
  namespace: kube-system
  labels:
    {{- include "blob.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: csi-blobfuse-proxy
  template:
    metadata:
      labels:
        app: csi-blobfuse-proxy
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: NotIn
                    values:
                      - virtual-kubelet
      initContainers:
        - name: prepare-binaries
{{- if hasPrefix "/" .Values.image.blob.repository }}
          image: "{{ .Values.image.baseRepo }}{{ .Values.image.blob.repository }}:{{ .Values.image.blob.tag }}"
{{- else }}
          image: "{{ .Values.image.blob.repository }}:{{ .Values.image.blob.tag }}"
{{- end }}
          command: ['sh', '-c', "cp /blobfuse-proxy/*.deb /tmp/"]
          volumeMounts:
            - mountPath: /tmp
              name: tmp-dir
      containers:
        - command:
            - nsenter
            - '--target'
            - '1'
            - '--mount'
            - '--uts'
            - '--ipc'
            - '--net'
            - '--pid'
            - '--'
            - sh
            - '-c'
            - |
              set -xe
              INSTALL_BLOBFUSE=${INSTALL_BLOBFUSE:-true}
              if (( "${INSTALL_BLOBFUSE}" == "true" ))
              then
                dpkg -i /tmp/packages-microsoft-prod.deb && apt-get install -y blobfuse=${BLOBFUSE_VERSION}
              fi
              dpkg -i /tmp/blobfuse-proxy.deb
              rm -f /tmp/packages-microsoft-prod.deb /tmp/blobfuse-proxy.deb
              mkdir -p /var/lib/kubelet/plugins/blob.csi.azure.com
              systemctl enable blobfuse-proxy
              systemctl start blobfuse-proxy

              SET_MAX_FILE_NUM=${SET_MAX_OPEN_FILE_NUM:-true}
              if (( "${SET_MAX_OPEN_FILE_NUM}" == "true" ))
              then
                sysctl -w fs.file-max=${MAX_FILE_NUM}
              fi

              # "waiting for blobfuse-proxy service to start"
              sleep 3s
              # tail blobfuse proxy logs
              journalctl -u blobfuse-proxy -f
{{- if hasPrefix "/" .Values.image.blob.repository }}
          image: "{{ .Values.image.baseRepo }}{{ .Values.image.blob.repository }}:{{ .Values.image.blob.tag }}"
{{- else }}
          image: "{{ .Values.image.blob.repository }}:{{ .Values.image.blob.tag }}"
{{- end }}
          imagePullPolicy: IfNotPresent
          name: sysctl-install-blobfuse-proxy
          env:
            - name: DEBIAN_FRONTEND
              value: "noninteractive"
            - name: INSTALL_BLOBFUSE
              value: "{{ .Values.node.blobfuseProxy.installBlobfuse }}"
            - name: BLOBFUSE_VERSION
              value: "{{ .Values.node.blobfuseProxy.blobfuseVersion }}"
            - name: SET_MAX_OPEN_FILE_NUM
              value: "{{ .Values.node.blobfuseProxy.setMaxOpenFileNum }}"
            - name: MAX_FILE_NUM
              value: "{{ .Values.node.blobfuseProxy.maxOpenFileNum }}"
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 10m
              memory: 1Mi
          securityContext:
            privileged: true
      hostNetwork: true
      hostPID: true
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-node-critical
      restartPolicy: Always
      tolerations:
        - operator: Exists
      volumes:
        - hostPath:
            path: /tmp
            type: DirectoryOrCreate
          name: tmp-dir
{{ end }}
