name: Windows Tests
on:
    pull_request: {}
    push: {}
jobs:
  build:
    strategy:
      matrix:
        go-versions: [1.16.x]
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v5
        with:
          go-version: ^1.16
        id: go
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Test
        run: |
          make blob-windows
      - name: Run Windows Unit Tests
        run: |
          go test -v -race ./pkg/...
