name: Windows Tests
on:
    pull_request: {}
    push: {}
permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        go-versions: [1.16.x]
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6
        with:
          go-version: ^1.16
        id: go
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Build Test
        run: |
          make blob-windows
      - name: Run Windows Unit Tests
        run: |
          go test -v -race ./pkg/...
